name: CI/CD Pipeline - Node App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (optional)
      run: echo "No tests yet"

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/my-node-app
          git pull origin main
          sudo docker stop my-node-app || true
          sudo docker rm my-node-app || true
          sudo docker build -t my-node-app .
          sudo docker run -d -p 8080:8080 --name my-node-app my-node-app
